### ISSUE TITLE
How to add a new translation?

### ISSUE THREAD

**Issue by kroupovka** [miniBloq/v0.83#5]
Hi guys, 
I translated the miniBloq for AERobot into Czech (Čeština) and I would like to share my translation - what's the best way? 
Thanks.

**Comment by miniBloq** [comment]
Hi, thanks! Please send it to nbloqs[at] gmail dot com and we can try to
integrate it.

**Comment by miniBloq** [comment]
Hi, thanks! Please send it to nbloqs[at] gmail dot com and we can try to integrate it.

**Comment by kroupovka** [comment]
merci :-) sent!

**Comment by miniBloq** [comment]
Thanks! Will try to integrate it in the upcoming weeks.
